### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by pay632006** [zggg1p/A-Domain-Adaption-Transfer-Learning-Bearing-Fault-Diagnosis-Model-Based-on-Wide-Convolution-Deep-Neu#3]
Could you please upload the data files that you used?

**Comment by zggg1p** [comment]
Of course. Baidu web disk link is as follows:
链接：https://pan.baidu.com/s/1zBjo5lawWTHbfryVPm0vkg 
提取码：jii8 
--来自百度网盘超级会员V4的分享
