### ISSUE TITLE
输入数据集相关问题

### ISSUE THREAD

**Issue by zy899** [zggg1p/A-Domain-Adaption-Transfer-Learning-Bearing-Fault-Diagnosis-Model-Based-on-Wide-Convolution-Deep-Neu#4]
作者您好，请问您模型输入的数据集中这个路径里数据集的名字80和100分别代表的是什么？如能解答不胜感激！
![image](https://user-images.githubusercontent.com/81020181/233541854-ca49a83f-8e68-4b89-889b-8be6f5c1e815.png)

**Comment by zggg1p** [comment]
100代表训练集中每类100个样本，
80代表训练集中每类80个样本



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zy899 ***@***.***&gt;
发送时间: 2023年4月21日 12:38
收件人: zggg1p/A-Domain-Adaption-Transfer-Learning-Bearing-Fault-Diagnosis-Model-Based-on-Wide-Convolution-Deep-Neu ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zggg1p/A-Domain-Adaption-Transfer-Learning-Bearing-Fault-Diagnosis-Model-Based-on-Wide-Convolution-Deep-Neu] 输入数据集相关问题 (Issue #4)





 
作者您好，请问您模型输入的数据集中这个路径里数据集的名字80和100分别代表的是什么？如能解答不胜感激！
